# Generated by Django 4.2 on 2023-04-30 12:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('CV_File', models.FileField(upload_to='pdfs/')),
                ('Photo_File', models.FileField(upload_to='photos/')),
                ('linkedln_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeS', models.CharField(choices=[('A', 'graphical charter'), ('B', 'Object 3D'), ('C', 'Scenarisation')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, unique=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProdApp.personnel')),
            ],
        ),
    ]
