# Generated by Django 4.2 on 2023-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0004_project_service_alter_services_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Photo',
            field=models.FileField(default='', upload_to='serices/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='TypeS',
            field=models.CharField(choices=[('Graphic charts', 'Graphic charts'), ('3D Modeling', '3D Modeling'), ('Scriptwriting', 'Scriptwriting')], max_length=20),
        ),
    ]
