# Generated by Django 4.2 on 2023-05-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0005_services_photo_alter_services_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='experience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personnel',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArtyProdApp.services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='Photo',
            field=models.FileField(upload_to='services/'),
        ),
    ]
