# Generated by Django 4.2 on 2023-05-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0006_personnel_experience_personnel_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='service',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.AddField(
            model_name='personnel',
            name='services',
            field=models.ManyToManyField(to='ArtyProdApp.services'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='ArtyProdApp.services'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArtyProdApp.team'),
            preserve_default=False,
        ),
    ]
