# Generated by Django 4.2 on 2023-05-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0008_remove_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='services',
        ),
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArtyProdApp.team'),
            preserve_default=False,
        ),
    ]
