# Generated by Django 4.2 on 2023-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0009_remove_personnel_services_remove_project_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='services',
            field=models.ManyToManyField(to='ArtyProdApp.services'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='ArtyProdApp.services'),
        ),
    ]
