# Generated by Django 4.2 on 2023-05-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0014_remove_personnel_services_alter_project_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArtyProdApp.signup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
