# Generated by Django 4.2 on 2023-05-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0020_rename_services_project_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ArtyProdApp.project'),
            preserve_default=False,
        ),
    ]
