# Generated by Django 4.2 on 2023-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0028_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service',
            field=models.ManyToManyField(blank=True, to='ArtyProdApp.services'),
        ),
    ]
