# Generated by Django 4.2 on 2023-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0029_alter_project_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.AddField(
            model_name='project',
            name='sevices',
            field=models.CharField(choices=[('Graphic charts', 'Graphic charts'), ('3D Modeling', '3D Modeling'), ('Scriptwriting', 'Scriptwriting')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
