# Generated by Django 4.2 on 2023-05-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0031_remove_project_sevices_project_sevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sevice',
            new_name='service',
        ),
    ]
