# Generated by Django 4.2 on 2023-05-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0032_rename_sevice_project_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ManyToManyField(to='ArtyProdApp.services'),
        ),
    ]
