# Generated by Django 4.2 on 2023-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0033_remove_project_service_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sender_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
