# Generated by Django 4.2 on 2023-05-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0034_project_sender_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sender_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
