# Generated by Django 4.2 on 2023-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProdApp', '0035_contact_sender_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('I', 'In-progress')], default='I', max_length=1),
        ),
    ]
